Removed old TUI program entries, improved pty-open

diff --git a/unix/.local/bin/pty-open b/unix/.local/bin/pty-open
--- a/unix/.local/bin/pty-open
+++ b/unix/.local/bin/pty-open
@@ -1,9 +1,16 @@
 #!/bin/sh
 # TODO: Check gobling equivalent of ? in regexp
-# terminal, has w3m, ext x?html? = w3m "$@"
 #terminal, has als, ext 7z|ace|ar|arc|bz2?|cab|cpio|cpt|deb|dgc|dmg|gz = als -- "$@" | "$PAGER"
 #terminal, has als, ext iso|jar|msi|pkg|rar|shar|tar|tgz|xar|xpi|xz|zip = als -- "$@" | "$PAGER"
 #  terminal, ext 1, has man = man "$1"
+
+test "$1" = '--' && shift
+
+if test $# -eq 0
+then
+  pty-open `fzf`
+  exit $?
+fi
 
 case "$1" in
   ########
@@ -49,7 +56,7 @@ case "$1" in
     then
       "$PAGER" "$@"
     else
-      echo 'Could not understand URI. Return to exit'
+      echo "Could not understand URI: $1.\nReturn to exit"
       read _
     fi
   ;;
